# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "caf3e53cdba6e881f38d874e95274499"
name = "demo"
application_url = "https://easier-exactly-superb-howard.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "helloworld-my.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://easier-exactly-superb-howard.trycloudflare.com/auth/callback",
  "https://easier-exactly-superb-howard.trycloudflare.com/auth/shopify/callback",
  "https://easier-exactly-superb-howard.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
